spring.application.name=finance-dashboard

# ==========================================
# CONEXÃO COM O BANCO DE DADOS (POSTGRES NO DOCKER)
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ==========================================
# Hibernate só precisa validar se o Java bate com o Banco
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURAÇÕES DO FLYWAY
# ==========================================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true